matrix:
  include:
    - name: "Linux Test"
      language: node_js
      node_js: "10.16.1"
      os: linux
      if: NOT commit_message =~ /^:hammer:/
      dist: xenial
      sudo: false
      install:
        - cd test
        - npm ci
    - name: "OSX Test"
      language: node_js
      node_js: "10.16.1"
      os: osx
      if: NOT commit_message =~ /^:hammer:/
      install:
        - cd test
        - npm ci
    # Windows is not supported on travis, but that's how it ment to be
    # - name: "Windows"
    #   os: windows
    #   script:
    #     - cd src
    #     - mingw32-make OS=Windows ARCH=64
    #     - cd ..
    - name: "Linux Build"
      os: linux
      dist: xenial
      env:
        - NEEDS_UPLOAD=true
        - UPLOAD_NAME=Linux
      if: commit_message =~ /^:hammer:/
      language: cpp
      compiler: gcc
      script:
        - cd src
        - make
        - cd ..
    - name: "OSX Build"
      os: osx
      env:
        - NEEDS_UPLOAD=true
        - UPLOAD_NAME=OSX
      if: commit_message =~ /^:hammer:/
      language: cpp
      compiler: clang++
      script:
        - cd src
        - make
        - cd ..


deploy:
  on:
    all_branches: true
    condition: $NEEDS_UPLOAD = true
  provider: releases
  name: "$UPLOAD_NAME Binaries"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file_glob: true
  file:
    - "src/build/bin/*"
