if: commit_message =~ /^:hammer:/

language: node_js

node_js:
  - "10.13.0"

matrix:
  include:
  - name: "Windows"
    os: windows
    before_install:
      - make OS=Windows ARCH=64
      - make OS=Windows ARCH=32
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
  - name: "MacOS"
    os: osx
    compiler: clang++


before_install:
  - make

install:
  - cd test
  - npm i

script:
  - npm test


deploy:
  - provider: releases
    name: "Binaries"
    body: $TRAVIS_COMMIT_MESSAGE
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    draft: true
    file:
      - "bin-linux64/libbullet.a"
      - "bin-mac64/libbullet.a"
      - "bin-win32/bullet.lib"
      - "bin-win64/bullet.lib"
