if: commit_message =~ /^:hammer:/

language: cpp


matrix:
  include:
  - name: "Windows"
    os: windows
    script:
      - mingw32-make OS=Windows ARCH=64
      - mingw32-make OS=Windows ARCH=32
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
  - name: "MacOS"
    os: osx
    compiler: clang++


script:
  - make


deploy:
  - provider: script
    skip_cleanup: true
    script:
      - ls -la
      - echo 1111111111111
      - ls -la build
      - echo 2222222222
      - ls -la build/bin
      - echo 33333333333
  - provider: releases
    name: "Binaries for $TRAVIS_OS_NAME"
    body: $TRAVIS_COMMIT_MESSAGE
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    draft: true
    file:
      - "build/bin/*"
